### ISSUE TITLE
Warning: Undefined array key "module"

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/sendgrid_integration#6]
I see this repeatedly in my logs:

> Warning: Undefined array key "module" in SendGridMailSystem->mail() (line 100 of /code/modules/contrib/sendgrid_integration/inc/sendgrid.mail.inc).

**Comment by laryn** [comment]
@ElusiveMind I've also linked a simple PR here for your consideration.

**Comment by ElusiveMind** [comment]
Will be reviewing these tomorrow. Been a busy few days with work and today is my anniversary celebration. Didn’t want you to think I forgot.

**Comment by laryn** [comment]
Happy anniversary!
